#!/bin/sh

# ========= WARNING: This file is auto-generated by AI !!! =========

# Simple build counter generator.
# Increments include/.build_counter and writes include/build_counter.h

COUNTER_FILE="include/.build_counter"
HEADER_FILE="include/os_build.h"

mkdir -p build
mkdir -p include

if [ ! -f "$COUNTER_FILE" ]; then
    echo 0 > "$COUNTER_FILE"
fi

COUNT=$(cat "$COUNTER_FILE" 2>/dev/null || echo 0)
# strip non-digits
COUNT=$(echo "$COUNT" | tr -cd '0-9')
if [ -z "$COUNT" ]; then
    COUNT=0
fi
NEW=$((COUNT + 1))

echo "$NEW" > "$COUNTER_FILE"
DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

cat > "$HEADER_FILE" <<EOF
#ifndef BUILD_H
#define BUILD_H

#define BUILD_NUMBER $NEW
#define BUILD_DATE "$DATE"

#define OS_NAME "MountainOS"
#define OS_VERSION "3.1.1"

#define OS_KRNL_NAME "Munt3"
#define OS_KRNL_VERSION "3.1.1"

#endif /* BUILD_H */
EOF

# Print a small message (Make will hide @-prefixed prints)
printf "Generated %s (BUILD_NUMBER=%s)\n" "$HEADER_FILE" "$NEW"
